# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 567931d1a8d5f7daab8f9654952e497b6dccde1882c97858e53f137c15987d838558328238304f19ce4251f782cc63ca269f7032b6a34fc5a02cd2bdcbaf9cfa

test:
  secret_key_base: bfe54baed2f4ee2d9c0f45352ccb22e8b665d2d92b9823fe7faeb1351de19dde7ce58ce25690a0cb56d653e1a176adc47887cc9a2a4a8ae07219abfc740b5649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
